### ISSUE TITLE
JSONDecodeError - (Need Help)

### ISSUE THREAD

**Issue by michael-makhoul** [dend/foggycam#41]
-

**Comment by kweitzner** [comment]
Control characters are qualified as character codes 0-31 so things like \n, \t, \r.  You've probably got a new line character or something that doesn't belong.

Maybe try starting with a fresh JSON file and typing rather than pasting it in.  You can also try adding a ,strict=False argument into the json loads function if that doesn't work.

More info here, hopefully this helps.
https://docs.python.org/3/library/json.html
If strict is false (True is the default), then control characters will be allowed inside strings. Control characters in this context are those with character codes in the 0–31 range, including '\t' (tab), '\n', '\r' and '\0'.
